Endspurt 21.12 (anpassungen Grammar name und testdatei)

diff --git a/.github/workflows/allinoneCICD.yml b/.github/workflows/allinoneCICD.yml
--- a/.github/workflows/allinoneCICD.yml
+++ b/.github/workflows/allinoneCICD.yml
@@ -93,6 +93,13 @@ jobs:
       - name: Run License and Header Check Script
         run: python3 scripts/license_check.py
 
+      - name: Verify Report File Exists
+        run: |
+          if [ ! -f "$GITHUB_WORKSPACE/license_reports/license_and_header_check_report.json" ]; then
+            echo "License and header check report not found. Exiting..."
+            exit 1
+          fi
+
 
       - name: Upload License and Header Check Report
         if: always()
